<?php 
session_start();
include '../connect.php';
$url = $_SERVER["REQUEST_URI"];
$_SESSION["url"]=$url;
if($_SESSION["user_id"]==1 || $_SESSION["user_id"]==2 || $_SESSION["user_id"]==3 || $_SESSION["user_id"]==4 )
{
$user_id=$_SESSION["user_id"];

}
else
{
echo "<script> location.href='../web/'; </script>";
}
?>
<?php

$product_id=$_GET['product_id'];
$sports=$_POST['sports'];
$type=$_POST['type'];
$product_name=$_POST['product_name'];
$stock=$_POST['stock'];
$return_type=$_POST['return_type'];
$show_price=$_POST['show_price'];
$original_price=$_POST['original_price'];
$discount=(($original_price-$show_price)/$original_price)*100;
$f1=$_POST['f1'];
$f2=$_POST['f2'];
$f3=$_POST['f3'];
$f4=$_POST['f4'];
$f5=$_POST['f5'];
$seller=$_POST['seller'];
$p1=$_POST['p1'];
$pi1=$_POST['pi1'];
$p2=$_POST['p2'];
$pi2=$_POST['pi2'];
$p3=$_POST['p3'];
$pi3=$_POST['pi3'];
$p4=$_POST['p4'];
$pi4=$_POST['pi4'];
$p5=$_POST['p5'];
$pi5=$_POST['pi5'];
$p6=$_POST['p6'];
$pi6=$_POST['pi6'];
$p7=$_POST['p7'];
$pi7=$_POST['pi7'];
$p8=$_POST['p9'];
$pi8=$_POST['pi8'];
$p9=$_POST['p9'];
$pi9=$_POST['pi9'];
$p10=$_POST['p10'];
$pi10=$_POST['pi10'];
$g1=$_POST['g1'];
$i1=$_POST['i1'];
$g2=$_POST['g2'];
$i2=$_POST['i2'];
$g3=$_POST['g3'];
$i3=$_POST['i3'];
$g4=$_POST['g4'];
$i4=$_POST['i4'];
$g5=$_POST['g5'];
$i5=$_POST['i5'];
$g6=$_POST['g6'];
$i6=$_POST['i6'];
$g7=$_POST['g7'];
$i7=$_POST['i7'];
$g8=$_POST['g9'];
$i8=$_POST['i8'];
$g9=$_POST['g9'];
$i9=$_POST['i9'];
$g10=$_POST['g10'];
$i10=$_POST['i10'];
$sizeset=$_POST['sizeset'];
$size1=$_POST['size1'];
$size2=$_POST['size2'];
$size3=$_POST['size3'];
$size4=$_POST['size4'];
$size5=$_POST['size5'];
$size6=$_POST['size6'];
$size7=$_POST['size7'];
$size8=$_POST['size8'];
$size9=$_POST['size9'];
$size10=$_POST['size10'];
$brand=$_POST['brand'];
$return_day=$_POST['return_day'];
$tag1=$_POST["tag1"];
$tag2=$_POST["tag2"];
$tag3=$_POST["tag3"];
$tag4=$_POST["tag4"]; 
$tag5=$_POST["tag5"];
$tag6=$_POST["tag6"];
$tag7=$_POST["tag7"];
$tag8=$_POST["tag8"];
$tag9=$_POST["tag9"];
$tag10=$_POST["tag10"];
$verify=0;
$update="UPDATE product_details SET sports='$sports',type='$type',stock='$stock',return_type='$return_type',name='$product_name',show_price='$show_price',original_price='$original_price',discount='$discount',f1='$f1',f2='$f2',f3='$f3',f4='$f4',f5='$f5',seller='$seller',p1='$p1',
pi1='$pi1',
p2='$p2',
pi2='$pi2',
p3='$p3',
pi3='$pi3',
p4='$p4',
pi4='$pi4',
p5='$p5',
pi5='$pi5',
p6='$p6',
pi6='$pi6',
p7='$p7',
pi7='$pi7',
p8='$p9',
pi8='$pi8',
p9='$p9',
pi9='$pi9',
p10='$p10',
pi10='$pi10',
g1='$g1',
i1='$i1',
g2='$g2',
i2='$i2',
g3='$g3',
i3='$i3',
g4='$g4',
i4='$i4',
g5='$g5',
i5='$i5',
g6='$g6',
i6='$i6',
g7='$g7',
i7='$i7',
g8='$g9',
i8='$i8',
g9='$g9',
i9='$i9',
g10='$g10',
i10='$i10',
sizeset='$sizeset',
tag1='$tag1',
tag2='$tag2',
tag3='$tag3',
tag4='$tag4',
tag5='$tag5',
tag6='$tag6',
tag7='$tag7',
tag8='$tag8',
tag9='$tag9',
tag10='$tag10',
verify='$verify',
size1='$size1',size2='$size2',size3='$size3',size4='$size4',size5='$size5',size6='$size6',size7='$size7',size8='$size8',size9='$size9',size10='$size10',
brand='$brand',return_day='$return_day' WHERE product_id='$product_id'";
if(mysqli_query($connect,$update))
{
echo "<script> alert('PRODUCT UPDATED') </script>";
echo "<script> location.href='updateproducthtml.php' </script>";
}
else
{
	echo "error ".mysqli_error($connect);
}


?>